"""Revision ID: 690655992280
Revises: d87034d6d38f
Create Date: 2025-09-04 17:50:33.153563
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "690655992280"
down_revision = "d87034d6d38f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_alerts_expires_at", "alerts", ["expires_at"], unique=False)
    op.create_index(
        "ix_alerts_product_status", "alerts", ["product_id", "status"], unique=False
    )
    op.create_index(
        "ix_alerts_user_status", "alerts", ["user_id", "status"], unique=False
    )
    op.create_index(
        "ix_consumptions_user_product",
        "consumptions",
        ["user_id", "product_id", "consumed_at"],
        unique=False,
    )
    op.create_index(
        "ix_products_expiration_date", "products", ["expiration_date"], unique=False
    )
    op.create_index(
        "ix_products_name_category", "products", ["name", "category_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_name_category", table_name="products")
    op.drop_index("ix_products_expiration_date", table_name="products")
    op.drop_index("ix_consumptions_user_product", table_name="consumptions")
    op.drop_index("ix_alerts_user_status", table_name="alerts")
    op.drop_index("ix_alerts_product_status", table_name="alerts")
    op.drop_index("ix_alerts_expires_at", table_name="alerts")
    # ### end Alembic commands ###
