"""Revision ID: d87034d6d38f
Revises: d0beba9e77b4
Create Date: 2025-09-04 17:41:19.993332
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d87034d6d38f"
down_revision = "d0beba9e77b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
